apiVersion: apps/v1
kind: Deployment
metadata:
  name: glare_app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: glare_app
  template:
    metadata:
      labels:
        app: glare_app
    spec:
      containers:
      - image: luminoussg/my-app:v1
        name: glare_app
        ports:
        - containerPort: 8080
          name: web
        - containerPort: 1935
          name: srt-tcp
          protocol: TCP
        - containerPort: 1935
          name: srt-udp
          protocol: UDP
        - containerPort: 4200
          name: srt-alt
          protocol: UDP 
