apiVersion: v1
kind: Service
metadata:
  name: glare_app
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 7861
    protocol: TCP
    name: web
  - port: 1935
    targetPort: 1935
    protocol: TCP
    name: srt-tcp
  - port: 1935
    targetPort: 1935
    protocol: UDP
    name: srt-udp
  - port: 4200
    targetPort: 4200
    protocol: UDP
    name: srt-alt
  selector:
    app: glare_app
  type: LoadBalancer
  loadBalancerIP: 192.168.31.197