apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - glare_app-deployment.yaml
  - glare_app-svc.yaml

namespace: default

commonLabels:
  app.kubernetes.io/name: glare_app
  app.kubernetes.io/instance: glare_app

images:
  - name: luminoussg/my-app
    newTag: v1